exports.handler = async (event, context) => {
    return {
     statusCode: 200,
     body: `{
        "pokemon": [
          {
            "nextid": "004",
            "id": "001",
            "name": "Bulbasaur",
            "image": "/images/Bulbasaur.svg",
            "type1": "Grass",
            "type2": "Poison",
            "weight": "6,9 kg",
            "height": "0,7 m",
            "move1": "Chlorophyll",
            "move2": "Overgrow",
            "description": "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.",
            "baseStats": {
              "hp": "045",
              "atk": "049",
              "def": "049",
              "satk": "065",
              "sdef": "065",
              "spd": "065"
            }
          },
          {
            "previd": "001",
            "nextid": "007",
            "id": "004",
            "name": "Charmander",
            "image": "/images/Charmander.svg",
            "type1": "Fire",
            "weight": "8,5 kg",
            "height": "0,6 m",
            "move1": "Mega-Punch",
            "move2": "Fire-Punch",
            "description": "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.",
            "baseStats": {
              "hp": "039",
              "atk": "052",
              "def": "043",
              "satk": "060",
              "sdef": "050",
              "spd": "065"
            }
          },
          {
            "previd": "004",
            "nextid": "012",
            "id": "007",
            "name": "Squirtle",
            "image": "/images/Squirtle.svg",
            "type1": "Water",
            "weight": "9,0 kg",
            "height": "0,5 m",
            "move1": "Torrent",
            "move2": "Rain-Dish",
            "description": "When it retracts its long neck into its Shell, it squirts out water with vigorous force.",
            "baseStats": {
              "hp": "044",
              "atk": "048",
              "def": "065",
              "satk": "050",
              "sdef": "064",
              "spd": "043"
            }
          },
          {
            "previd": "007",
            "nextid": "025",
            "id": "012",
            "name": "Butterfree",
            "image": "/images/Butterfree.svg",
            "type1": "Bug",
            "type2": "Flying",
            "weight": "32,0 kg",
            "height": "1,1 m",
            "move1": "Compound",
            "move2": "Tinted-lens",
            "description": "In batle, it faps its wings at great speed to release highl toxic dust into tne air.",
            "baseStats": {
              "hp": "060",
              "atk": "045",
              "def": "050",
              "satk": "095",
              "sdef": "080",
              "spd": "070"
            }
          },
          {
            "previd": "012",
            "nextid": "092",
            "id": "025",
            "name": "Pikachu",
            "image": "/images/Pikachu.svg",
            "type1": "Electric",
            "type2": "",
            "weight": "6.0 kg",
            "height": "0,4 m",
            "move1": "Mega-Punch",
            "move2": "Pay-Day",
            "description": "Pikochu that can generate powerful electricity have cheek socs that are extra soft and super stretchy.",
            "baseStats": {
              "hp": "035",
              "atk": "055",
              "def": "040",
              "satk": "050",
              "sdef": "050",
              "spd": "050"
            }
          },
          {
            "previd": "025",
            "nextid": "132",
            "id": "092",
            "name": "Gastly",
            "image": "/images/Gastly.svg",
            "type1": "Ghost",
            "type2": "Poison",
            "weight": "0,1 kg",
            "height": "1,3 m",
            "move1": "Levtate",
            "move2": "",
            "description": "Born from gases, anyone would faint if engufed by its gaseous body, which contains poison",
            "baseStats": {
              "hp": "030",
              "atk": "035",
              "def": "030",
              "satk": "100",
              "sdef": "035",
              "spd": "080"
            }
          },
          {
            "previd": "092",
            "nextid": "152",
            "id": "132",
            "name": "Ditto",
            "image": "/images/Ditto.svg",
            "type1": "Normal",
            "type2": "",
            "weight": "4,0 kg",
            "height": "0,3 m",
            "move1": "Limber",
            "move2": "Imposter",
            "description": "It can reconstitute its entire cellular structure to change ito what it sees, but it returns to normal when it relaxes.",
            "baseStats": {
              "hp": "048",
              "atk": "048",
              "def": "048",
              "satk": "048",
              "sdef": "048",
              "spd": "048"
            }
          },
          {
            "previd": "132",
            "nextid": "304",
            "id": "152",
            "name": "Mew",
            "image": "/images/Mew.svg",
            "type1": "Psychic",
            "type2": "",
            "weight": "4,0 kg",
            "height": "0,4 m",
            "move1": "Synchronize",
            "move2": "",
            "description": "When viewed through a microscope, this pokémon´s short, fine, delicate hair can be seen.",
            "baseStats": {
              "hp": "100",
              "atk": "100",
              "def": "100",
              "satk": "100",
              "sdef": "100",
              "spd": "100"
            }
          },
          {
            "previd": "152",
            "id": "304",
            "nextid": "324",
            "name": "Aron",
            "image": "/images/Aron.svg",
            "type1": "Steel",
            "type2": "Rock",
            "weight": "60,0 kg",
            "height": "0,4 m",
            "move1": "Sturdy",
            "move2": "Rock-head",
            "description": "It eats iron are - and sometimes railroad tracks - to build up the steel armor that protects its body.",
            "baseStats": {
              "hp": "050",
              "atk": "070",
              "def": "100",
              "satk": "040",
              "sdef": "040",
              "spd": "030"
            }
          },
      
          {
            "previd": "304",
            "nextid": "405",
            "id": "324",
            "name": "Torkoal",
            "image": "/images/Torkoal.png",
            "type1": "Fire",
            "weight": "80,4 kg",
            "height": "0,5 m",
            "move1": "White Smoke",
            "move2": "Shell Armor",
            "description": "Torkoal digs through mountains in search of coal. If it finds some, it fills hollow spaces on its shell with the coal and burns it to produce energy.",
            "baseStats": {
              "hp": "70",
              "atk": "85",
              "def": "140",
              "satk": "85",
              "sdef": "70",
              "spd": "20"
            }
          },
          {
            "previd": "324",
            "nextid": "446",
            "id": "405",
            "name": "Luxray",
            "image": "/images/Luxray.png",
            "type1": "Electric",
            "weight": "42,0 kg",
            "height": "1,4 m",
            "move1": "Intimidate",
            "move2": "Rivalry",
            "description": "It has eyes which can see through anything. It spots and captures prey hiding behind objects.",
            "baseStats": {
              "hp": "80",
              "atk": "120",
              "def": "79",
              "satk": "95",
              "sdef": "79",
              "spd": "70"
            }
          },
          {
            "previd": "405",
            "nextid": "468",
            "id": "446",
            "name": "Munchlax",
            "image": "/images/Munchlax.png",
            "type1": "Normal",
            "weight": "105,0 kg",
            "height": "0,6 m",
            "move1": "Pickup",
            "move2": "Thick Fat",
            "description": "It wolfs down its weight in food once a day, swallowing food whole with almost no chewing.",
            "baseStats": {
              "hp": "135",
              "atk": "85",
              "def": "40",
              "satk": "40",
              "sdef": "85",
              "spd": "5"
            }
          },
          {
            "previd": "446",
            "nextid": "579",
            "id": "468",
            "name": "Togekiss",
            "image": "/images/Togekiss.png",
            "type1": "Fairy",
            "type2": "Flying",
            "weight": "38,0 kg",
            "height": "1,5 m",
            "move1": "Hustle",
            "move2": "Serene Grace",
            "description": "It will never appear where there is strife. Its sightings have become rare recently.",
            "baseStats": {
              "hp": "85",
              "atk": "50",
              "def": "95",
              "satk": "120",
              "sdef": "115",
              "spd": "80"
            }
          },
          {
            "previd": "468",
            "nextid": "631",
            "id": "579",
            "name": "Reuniclus",
            "image": "/images/Reuniclus.png",
            "type1": "Psychic",
            "weight": "20,1 kg",
            "height": "1,0 m",
            "move1": "Overcoat",
            "move2": "Magic Guard",
            "description": "The special fluid covering its body changes into a variety of poisons as Reuniclus's mental state worsens.",
            "baseStats": {
              "hp": "110",
              "atk": "65",
              "def": "75",
              "satk": "125",
              "sdef": "85",
              "spd": "30"
            }
          },
          {
            "previd": "579",
            "nextid": "701",
            "id": "631",
            "name": "Heatmor",
            "image": "/images/Heatmor.png",
            "type1": "Fire",
            "weight": "58,0 kg",
            "height": "1,4 m",
            "move1": "Flash Fire",
            "move2": "White Smoke",
            "description": "Using their very hot, flame-covered tongues, they burn through Durant's steel bodies and consume their insides.",
            "baseStats": {
              "hp": "85",
              "atk": "97",
              "def": "66",
              "satk": "105",
              "sdef": "66",
              "spd": "65"
            }
          },
          {
            "previd": "631",
            "nextid": "711",
            "id": "701",
            "name": "Hawlucha",
            "image": "/images/Hawlucha.png",
            "type1": "Fighting",
            "type2": "Flying",
            "weight": "21,5 kg",
            "height": "0,8 m",
            "move1": "Limber",
            "move2": "Unburden",
            "description": "Although its body is small, its proficient fighting skills enable it to keep up with big bruisers like Machamp and Hariyama.",
            "baseStats": {
              "hp": "78",
              "atk": "92",
              "def": "75",
              "satk": "74",
              "sdef": "63",
              "spd": "118"
            }
          },
          {
            "previd": "701",
            "nextid": "735",
            "id": "711",
            "name": "Gourgeist",
            "image": "/images/Gourgeist.png",
            "type1": "Ghost",
            "type2": "Grass",
            "weight": "12,5 kg",
            "height": "0,9 m",
            "move1": "Pickup",
            "move2": "Insomnia",
            "description": "Singing in eerie voices, they wander town streets on the night of the new moon. Anyone who hears their song is cursed.",
            "baseStats": {
              "hp": "65",
              "atk": "90",
              "def": "122",
              "satk": "58",
              "sdef": "75",
              "spd": "84"
            }
          },
          {
            "previd": "711",
            "nextid": "766",
            "id": "735",
            "name": "Gumshoos",
            "image": "/images/Gumshoos.png",
            "type1": "Normal",
            "weight": "14,2 kg",
            "height": "0,7 m",
            "move1": "Adaptability",
            "move2": "Stakeout",
            "description": "When it finds a trace of its prey, it patiently stakes out the location. But it's always snoozing by nightfall.",
            "baseStats": {
              "hp": "88",
              "atk": "110",
              "def": "60",
              "satk": "55",
              "sdef": "60",
              "spd": "45"
            }
          },
          {
            "previd": "735",
            "id": "766",
            "nextid": "772",
            "name": "Passimian",
            "image": "/images/Passimian.png",
            "type1": "Fighting",
            "type2": "",
            "weight": "82,8 kg",
            "height": "2,0 m",
            "move1": "Receiver",
            "move2": "Defiant",
            "description": "They form groups of roughly 20 individuals. Their mutual bond is remarkable—they will never let down a comrade.",
            "baseStats": {
              "hp": "100",
              "atk": "120",
              "def": "90",
              "satk": "40",
              "sdef": "60",
              "spd": "80"
            }
          },
          {
            "previd": "766",
            "nextid": "789",
            "id": "772",
            "name": "Codigo Cero",
            "image": "/images/Codigocero..png",
            "type1": "Normal",
            "weight": "120,5 kg",
            "height": "1,9 m",
            "move1": "Battle Armor",
            "move2": "Download",
            "description": "It was constructed to synthesize the strengths of various other Pokémon, enabling it to adapt to any situation.",
            "baseStats": {
              "hp": "95",
              "atk": "95",
              "def": "95",
              "satk": "95",
              "sdef": "95",
              "spd": "59"
            }
          },
          {
            "previd": "772",
            "nextid": "791",
            "id": "789",
            "name": "Cosmoem",
            "image": "/images/Cosmoem.png",
            "type1": "Psychic",
            "type2": "",
            "weight": "2204,4 kg",
            "height": "0,2 m",
            "move1": "Sturdy",
            "move2": "",
            "description": "In ages past, it was called the cocoon of the stars. It's said to be a hardy Pokémon that can survive any sort of hardship.",
            "baseStats": {
              "hp": "43",
              "atk": "29",
              "def": "131",
              "satk": "29",
              "sdef": "131",
              "spd": "37"
            }
          },
          {
            "previd": "789",
            "nextid": "800",
            "id": "791",
            "name": "Solgaleo",
            "image": "/images/Solgaleo.png",
            "type1": "Psychic",
            "type2": "Steel",
            "weight": "230,0 kg",
            "height": "3,4 m",
            "move1": "Full Metal Body",
            "move2": "",
            "description": "Its wings are spread wide and striking a more aggressive pose. The changes in its behavior are linked to its gratitude for the light of the Alola region.",
            "baseStats": {
              "hp": "137",
              "atk": "137",
              "def": "107",
              "satk": "113",
              "sdef": "89",
              "spd": "97"
            }
          },
          {
            "previd": "791",
            "nextid": "803",
            "id": "800",
            "name": "Necrozma",
            "image": "/images/Necrozma.png",
            "type1": "Psychic",
            "type2": "",
            "weight": "230,0 kg",
            "height": "3,8 m",
            "move1": "Prism Armor",
            "move2": "",
            "description": "Light is apparently the source of its energy. It has an extraordinarily vicious disposition and is constantly firing off laser beams.",
            "baseStats": {
              "hp": "97",
              "atk": "107",
              "def": "101",
              "satk": "127",
              "sdef": "89",
              "spd": "79"
            }
          },
          {
            "previd": "800",
            "nextid": "807",
            "id": "803",
            "name": "Poipole",
            "image": "/images/Poipole.png",
            "type1": "Poison",
            "type2": "",
            "weight": "1,8 kg",
            "height": "0,6 m",
            "move1": "Beast Boost",
            "move2": "",
            "description": "An Ultra Beast that lives in a different world, it cackles wildly as it sprays its opponents with poison from the needles on its head.",
            "baseStats": {
              "hp": "67",
              "atk": "73",
              "def": "67",
              "satk": "73",
              "sdef": "67",
              "spd": "73"
            }
          },
          {
            "previd": "803",
            "nextid": "813",
            "id": "807",
            "name": "Zeraora",
            "image": "/images/Zeraora.png",
            "type1": "Electric",
            "type2": "",
            "weight": "44,5 kg",
            "height": "1,5 m",
            "move1": "Volt Absorb",
            "move2": "",
            "description": "It electrifies its claws and tears its opponents apart with them. Even if they dodge its attack, they'll be electrocuted by the flying sparks.",
            "baseStats": {
              "hp": "88",
              "atk": "112",
              "def": "75",
              "satk": "102",
              "sdef": "80",
              "spd": "143"
            }
          },
          {
            "previd": "807",
            "nextid": "826",
            "id": "813",
            "name": "Scorbunny",
            "image": "/images/Scorbunny.png",
            "type1": "Fire",
            "type2": "",
            "weight": "4,5 kg",
            "height": "0,3 m",
            "move1": "Blaze",
            "move2": "Libero",
            "description": "It's just full of energy, enough to get tired out from running around even when indoors. When it's bursting with energy, its flames turn white-hot.",
            "baseStats": {
              "hp": "50",
              "atk": "71",
              "def": "40",
              "satk": "40",
              "sdef": "40",
              "spd": "69"
            }
          },
          {
            "previd": "813",
            "nextid": "838",
            "id": "826",
            "name": "Orbeetle",
            "image": "/images/Orbeetle.png",
            "type1": "Bug",
            "type2": "Psychic",
            "weight": "40,8 kg",
            "height": "0,4 m",
            "move1": "Swarm",
            "move2": "Telepathy",
            "description": "It emits psychic energy to observe and study what's around it—and what's around it can include things over six miles away.",
            "baseStats": {
              "hp": "60",
              "atk": "45",
              "def": "110",
              "satk": "80",
              "sdef": "120",
              "spd": "90"
            }
          },
          {
            "previd": "826",
            "nextid": "849",
            "id": "838",
            "name": "Carkol",
            "image": "/images/Carkol.png",
            "type1": "Rock",
            "type2": "Fire",
            "weight": "78,0 kg",
            "height": "1,1 m",
            "move1": "Steam Engine",
            "move2": "Flame Body",
            "description": "It forms coal inside its body. Coal dropped by this Pokémon once helped fuel the lives of people in the Galar region.",
            "baseStats": {
              "hp": "80",
              "atk": "60",
              "def": "90",
              "satk": "60",
              "sdef": "70",
              "spd": "50"
            }
          },
          {
            "previd": "838",
            "id": "849",
            "nextid": "856",
            "name": "Toxtricity",
            "image": "/images/Toxtricity.png",
            "type1": "Electric",
            "type2": "Poison",
            "weight": "40,0 kg",
            "height": "1,6 m",
            "move1": "Punk Rock",
            "move2": "Plus",
            "description": "Capable of generating 15,000 volts of electricity, this Pokémon looks down on all that would challenge it.",
            "baseStats": {
              "hp": "75",
              "atk": "98",
              "def": "70",
              "satk": "114",
              "sdef": "70",
              "spd": "75"
            }
          },
          {
            "previd": "849",
            "nextid": "872",
            "id": "856",
            "name": "Hatenna",
            "image": "/images/Hatenna.png",
            "type1": "Psychic",
            "type2": "",
            "weight": "3,4 kg",
            "height": "0,4 m",
            "move1": "Healer",
            "move2": "Anticipation",
            "description": "Via the protrusion on its head, it senses other creatures' emotions. If you don't have a calm disposition, it will never warm up to you.",
            "baseStats": {
              "hp": "42",
              "atk": "30",
              "def": "45",
              "satk": "56",
              "sdef": "53",
              "spd": "39"
            }
          },
          {
            "previd": "856",
            "nextid": "874",
            "id": "872",
            "name": "Snorlax",
            "image": "/images/Snorlax.png",
            "type1": "Normal",
            "type2": "",
            "weight": "460,0 kg",
            "height": "2,1 m",
            "move1": "Immunity",
            "move2": "Thick Fat",
            "description": "It is not satisfied unless it eats over 880 pounds of food every day. When it is done eating, it goes promptly to sleep.",
            "baseStats": {
              "hp": "160",
              "atk": "110",
              "def": "65",
              "satk": "65",
              "sdef": "110",
              "spd": "30"
            }
          },
          {
            "previd": "872",
            "nextid": "886",
            "id": "874",
            "name": "Eternatus",
            "image": "/images/Eternatus.png",
            "type1": "Poison",
            "type2": "Dragon",
            "weight": "950,0 kg",
            "height": "20,0 m",
            "move1": "Pressure",
            "move2": "",
            "description": "Infinite amounts of energy pour from this Pokémon's enlarged core, warping the surrounding space-time.",
            "baseStats": {
              "hp": "140",
              "atk": "85",
              "def": "95",
              "satk": "145",
              "sdef": "95",
              "spd": "130"
            }
          },
          {
            "previd": "874",
            "nextid": "891",
            "id": "886",
            "name": "Zacian",
            "image": "/images/Zacian.png",
            "type1": "Fairy",
            "type2": "Steel",
            "weight": "1100,0 kg",
            "height": "2,8 m",
            "move1": "Intrepid Sword",
            "move2": "",
            "description": "This Pokémon's sword exudes a golden gleam that can dazzle its opponents. It has a white fur mane, and its fur sparkles.",
            "baseStats": {
              "hp": "92",
              "atk": "170",
              "def": "115",
              "satk": "80",
              "sdef": "115",
              "spd": "148"
            }
          },
          {
            "previd": "886",
            "nextid": "894",
            "id": "891",
            "name": "Kubfu",
            "image": "/images/Kubfu.png",
            "type1": "Fighting",
            "type2": "",
            "weight": "12,0 kg",
            "height": "0,6 m",
            "move1": "Inner Focus",
            "move2": "",
            "description": "It's an extremely stubborn and strong-willed Pokémon. It will never show weakness in battle no matter how wounded it is.",
            "baseStats": {
              "hp": "60",
              "atk": "90",
              "def": "60",
              "satk": "53",
              "sdef": "50",
              "spd": "72"
            }
          },
          {
            "previd": "891",
            "nextid": "896",
            "id": "894",
            "name": "Regieleki",
            "image": "/images/Regieleki.png",
            "type1": "Electric",
            "type2": "",
            "weight": "145,0 kg",
            "height": "1,2 m",
            "move1": "Transistor",
            "move2": "",
            "description": "It zooms directly through the air at unbelievable speeds. Regieleki has been compared to lightning bolts.",
            "baseStats": {
              "hp": "80",
              "atk": "100",
              "def": "50",
              "satk": "100",
              "sdef": "50",
              "spd": "200"
            }
          },
          {
            "previd": "894",
            "nextid": "898",
            "id": "896",
            "name": "Glastrier",
            "image": "/images/Glastrier.png",
            "type1": "Ice",
            "type2": "",
            "weight": "800,0 kg",
            "height": "2,2 m",
            "move1": "Chilling Neigh",
            "move2": "",
            "description": "The heavy fog on its back grows denser the longer it stays in a chilly place. Glastrier is said to be the steed of the frost.",
            "baseStats": {
              "hp": "100",
              "atk": "145",
              "def": "130",
              "satk": "65",
              "sdef": "110",
              "spd": "30"
            }
          },
          {
            "previd": "896",
            "nextid": "900",
            "id": "898",
            "name": "Calyrex",
            "image": "/images/Calyrex.png",
            "type1": "Psychic",
            "type2": "Grass",
            "weight": "7,7 kg",
            "height": "1,1 m",
            "move1": "Unnerve",
            "move2": "",
            "description": "It's capable of using psychokinetic powers to generate energy in the form of psychic ice. It then uses this energy to control its body.",
            "baseStats": {
              "hp": "100",
              "atk": "80",
              "def": "80",
              "satk": "80",
              "sdef": "80",
              "spd": "80"
            }
          },
          {
            "previd": "898",
            "id": "900",
            "name": "Spectrier",
            "image": "/images/Spectrier.png",
            "type1": "Ghost",
            "type2": "",
            "weight": "44,5 kg",
            "height": "2,0 m",
            "move1": "Grim Neigh",
            "move2": "",
            "description": "It emits psychic energy to observe and study what's around it—and what's around it can include things over six miles away.",
            "baseStats": {
              "hp": "100",
              "atk": "65",
              "def": "60",
              "satk": "145",
              "sdef": "80",
              "spd": "130"
            }
          }
       
        ]
      }
      `,
    }
   }